# Generated by Django 5.0.7 on 2024-07-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField(unique=True)),
                ('usr_name', models.CharField(max_length=30)),
                ('usr_gender', models.CharField(max_length=6)),
                ('usr_mobile', models.IntegerField()),
                ('usr_email', models.EmailField(max_length=254)),
                ('usr_education', models.CharField(max_length=10)),
                ('usr_skill', models.BooleanField()),
                ('usr_address', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
