# Generated by Django 5.0.7 on 2024-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_usr_profile_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_profile',
            name='usr_mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='usr_profile',
            name='usr_skill',
            field=models.CharField(max_length=50),
        ),
    ]
