# Generated by Django 5.0.7 on 2024-07-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_usr_profile_usr_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usr_profile',
            name='usr_id',
            field=models.IntegerField(),
        ),
    ]
